### ISSUE TITLE
jobs: Catkin install job stage fails

### ISSUE THREAD

**Issue by jbohren** [jbohren-forks/catkin_tools#9]
@wjwwood https://github.com/catkin/catkin_tools/pull/196#issuecomment-113672598

> While testing it out I also got this traceback:

>```
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.3.0', 'console_scripts', 'catkin')()
  File "/Library/Python/2.7/site-packages/catkin_tools/commands/catkin.py", line 219, in main
    sys.exit(args.main(args) or 0)
  File "/Library/Python/2.7/site-packages/catkin_tools/verbs/catkin_build/cli.py", line 337, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/Library/Python/2.7/site-packages/catkin_tools/verbs/catkin_build/build.py", line 334, in build_isolated_workspace
    context, pkg, pkg_path, context.devel_space_abs)
  File "/Library/Python/2.7/site-packages/catkin_tools/jobs/catkin.py", line 604, in create_catkin_tools_bootstrap_job
    cwd=build_space))
TypeError: __init__() got an unexpected keyword argument 'command'
```

> Looking into it now.

**Comment by jbohren** [comment]
This should be fixed by  fc7bc72
